### PR TITLE
MNT: Re-rendered with conda-smithy 3.0.0 and pinning 2018.04.16

### PR DESCRIPTION
**Pull request by jakirkham**
xref: https://github.com/conda-forge/conda-smithy-feedstock/pull/91#issuecomment-382124536

### CODE REVIEW

**Comment by scopatz** [comment]
Does this need the build number to be increased? Or does it not matter?

**Comment by jakirkham** [comment]
Shouldn't matter, but can add one if you like.

**Comment by scopatz** [comment]
Naw, don't bother :smile:

**Comment by jakirkham** [comment]
Ok, thanks. :)

**Pull request merged**
