### PR TITLE
Regenerate recipe

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR updates AppVeyor's template using latest master conda-smithy.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Today's XKCD should be conda-forge's logo: http://imgs.xkcd.com/comics/tools.png

**Comment by pelson** [comment]
> Today's XKCD should be conda-forge's logo: http://imgs.xkcd.com/comics/tools.png

Amazing! That is how it all feels sometimes!

**Comment by pelson** [comment]
Congratulations @ocefpaf! First cycle of "fix the generator, apply the fix, bask in glory!" :wink:

**Comment by ocefpaf** [comment]
> Congratulations @ocefpaf! First cycle of "fix the generator, apply the fix, bask in glory!" :wink: 

I enjoyed using `conda-smithy`!  Thanks for all the effort you put into it.

**Pull request merged**
