### PR TITLE
v3.32.0 requires jsonschema

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

---

It was added upstream in `environment.yml` but yesterday's bot PR was automerged

https://github.com/conda-forge/conda-smithy/blob/85ddb5deabda9ab58ae6ec898e2a1e33393117b7/environment.yml#L36

xref: #281, https://github.com/conda-forge/conda-smithy/issues/1866

I didn't rerender because it was just rerendered yesterday

### CODE REVIEW

**Comment by beckermr** [comment]
Thank you! We'll need a repodata patch too. Are we also missing pydantic?

cc @jaimergp

**Comment by beckermr** [comment]
I can make the repodata patch later.

**Comment by isuruf** [comment]
pydantic is needed for development, but not for users.

**Comment by jdblischak** [comment]
> I can make the repodata patch later.

@beckermr thanks!

**Comment by jdblischak** [comment]
Also, FWIW, I dislike enabling automerge for critical feedstocks like this one. To me automerge is useful for maintaining less critical feedstocks whose PRs might languish. A conda-smithy update PR is too important to be forgotten about. A human review of the changes introduced in v3.32.0 would hopefully have caught the addition of jsonschema to `environment.yml`. IMO having to repodata patch after, even if infrequent, is so much more trouble than reviewing the PRs prior to merging. I have lots of CI jobs that depend on conda-smithy, so I'd be willing to commit to reviewing future PRs if automerge were disabled.

**Comment by jdblischak** [comment]
Documenting that this has been fully resolved: repodata patch was submitted and merged in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/683. Thanks @beckermr!

**Pull request merged**
