### PR TITLE
Update to v0.3.

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by pelson** [comment]
As with #1, this has failed on Windows. Needs some investigation (though I suspect we've seen it before @ocefpaf):

```
    https://github.com/conda/conda-build/issues
 
Include the output of the command 'conda info' in your report.
 
 
Traceback (most recent call last):
  File "C:\conda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 190, in main
    args_func(args, p)
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 468, in args_func
    args.func(args, p)
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "C:\conda\lib\site-packages\conda_build\build.py", line 392, in build
    source.provide(m.path, m.get_section('source'))
  File "C:\conda\lib\site-packages\conda_build\source.py", line 266, in provide
    git_source(meta, recipe_dir)
  File "C:\conda\lib\site-packages\conda_build\source.py", line 115, in git_source
    cwd=recipe_dir, check_exit_code=True)
  File "C:\conda\lib\site-packages\conda_build\utils.py", line 231, in execute
    output=(stdout, stderr))
subprocess.CalledProcessError: Command '['C:\\cygwin\\bin\\git.exe', 'clone', '--mirror', 'https://github.com/conda-forge/conda-smithy.git', '/cygdrive/c/conda/conda-bld/git_cache/__github.com_conda-forge_conda-smithy.git']' returned non-zero exit status 3328
Command exited with code 1
```

**Comment by ocefpaf** [comment]
We had that issue before and our solution was to delete AppVeyor's cygwin.  Then conda-build was [fixed](https://github.com/asmeurer/conda-build/commit/1c6f5c2f617eeab3b70bdb2a62cc0dcf7d7ae797) and we could leave AppVeyor as is.  After a while this issue cropped back up and since then I gave up cygwin entirely.  We should add this to our template:

`- cmd: rmdir C:\cygwin /s /q`

It is an ugly hack, but...  (I don't really know how to defend that :grimacing:)

**Comment by ocefpaf** [comment]
Should I just submit that change here now?

**Comment by pelson** [comment]
> Should I just submit that change here now?

If I were doing it, I'd run conda-smithy from source, change https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/appveyor.yml.tmpl and then run ```conda-smithy regenerate``` on the feedstock. Ultimately, you will need to submit 1 PR to conda-smithy, and 1 PR to conda-smithy-feedstock.

**Comment by ocefpaf** [comment]
OK. Let me try that.  If I crash and burn I will cry for help.

**Comment by pelson** [comment]
> OK. Let me try that. If I crash and burn I will cry for help.

I'm here to catch you :fire_engine: :smile:

**Pull request merged**
