### PR TITLE
Update to v0.8.2

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by ocefpaf** [comment]
When I get 3 e-mails at the same time: `PR` &rarr; `New release` &rarr; `feedstock update` I think I am living a science fiction tale :wink:

**Comment by pelson** [comment]
Release often and all :smile: 
3 times today isn't too bad I think :laughing:

**Comment by ocefpaf** [comment]
Just one [minor bump](https://github.com/conda-forge/staged-recipes/issues/259) along the way. But I like the streamlined release workflow.

**Comment by pelson** [comment]
Spotted that. Thanks for fixing it @ocefpaf. I'm sure we will get PRs getting friendly linting issues in many feedstocks as a result too :smile:

**Pull request merged**
