### PR TITLE
run full tests

### PR DESCRIPTION
**Pull request by CJ-Wright**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge/conda-smithy I'm not certain what is going wrong here. I'm trying to get it to run the full test suite (so that conda-build can check against this and not merge a breaking tag).

**Comment by isuruf** [comment]
I don't think the `tests` are packaged.

**Comment by CJ-Wright** [comment]
Ah ok, I guess I should add that.

**Comment by CJ-Wright** [comment]
@conda-forge/core could I get some help with these tests. I think it would be great to have this, so we can test against it on upstream dependencies to prevent breakage.

**Comment by CJ-Wright** [comment]
need to set git config see: https://github.com/regro/rever/blob/master/.circle.yml#L19

**Comment by CJ-Wright** [comment]
Hmm this seems to now work with the git things, but the amount of files being produced is off.

**Comment by beckermr** [comment]
We're running tests now so closing this.

**Pull request closed without merging**
