### PR TITLE
conda-smithy v3.2.1

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Merge only after success.

This pull request was auto-generated by [rever](https://regro.github.io/rever-docs/)

### CODE REVIEW

**Comment by isuruf** [comment]
Can you rerender this PR with v3.2.1?

**Comment by isuruf** [comment]
> Added support for rendering feedstock recipes for Azure pipelines.  
  Presently this is enabled globally for all feedstocks going forward by default.
  Azure builds are configured to not publish artifacts to anaconda.org

I don't think it's a good idea to release this without disabling reporting back especially since the feedstock maintainers and even core members don't have control over azure builds.

**Comment by mariusvniekerk** [comment]
The feedstocks already registered have reporting disabled

**Comment by isuruf** [comment]
Yes, but when this is version is released, new feedstocks will have reporting enabled and maintainers and core don't have control to even restart a build.

**Comment by isuruf** [comment]
Hmm, I don't see a azure build for conda-smithy. @mariusvniekerk, can you enable reporting for this feedstock so that we can see what happens?

**Comment by jakirkham** [comment]
Should this be closed in light of PR ( https://github.com/conda-forge/conda-smithy-feedstock/pull/116 ) or is it still needed for some reason?

**Comment by scopatz** [comment]
Yeah let's close.

**Pull request closed without merging**
