### PR TITLE
conda-smithy v3.1.1

### PR DESCRIPTION
**Pull request by scopatz**
Merge only after success.

This pull request was auto-generated by [rever](https://regro.github.io/rever-docs/)

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks.

Is this done as part of rever too?

**Comment by scopatz** [comment]
No problem! Yes, it is.

**Comment by jakirkham** [comment]
That's amazing. Thanks for doing that. :)

**Comment by scopatz** [comment]
My pleasure!

**Comment by scopatz** [comment]
rever can also do pypi releases too, if that is something you need.

**Pull request merged**
